### PR TITLE
Dockerized the application

### PR DESCRIPTION
**Pull request by yuvicc**
Is this okay? 
@SANTHOSH17-DOT 

#8

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
- Docker compose file should be used 
- Run `go run main.go host` as well.

**Comment by yuvicc** [comment]
I guess if we run

`
docker compose build
`

which will build the image 
After that if we run

`
docker compose run --rm are-you-bombed
`

then the "go run main.go host" will also run

**Comment by yuvicc** [comment]
Please review this PR @SANTHOSH17-DOT

**Comment by SANTHOSH17-DOT** [comment]
It doesn't work that way @i-am-yuvi 
We should add a docker-compose file to the project that uses the image(Dockerfile)
You may refer to this [example](https://firehydrant.com/blog/develop-a-go-app-with-docker-compose/)

**Comment by yuvicc** [comment]
Okay

**Pull request closed without merging**
