### PR TITLE
Dockerized the application

### PR DESCRIPTION
**Pull request by yuvicc**
## Describe your changes
 
Dockerized the application:

- Generated zip bombs
- Run the server

## Issue ticket number and link

#8 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Will this be part of a product update?

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
image
- Generate both the type of zip bombs within the container
-  You may not build the go application because the **host** command line parameter needs to be given. 
- Use docker compose file to run the container
- Port should be taken from the env file
Please do the above changes

**Comment by yuvicc** [comment]
Sure i'll do that.

**Comment by yuvicc** [comment]
Is this okay @SANTHOSH17-DOT? Please check.

**Comment by yuvicc** [comment]
resolving the conflicts

**Pull request closed without merging**
